let planets_info = [
	"The sun is the star in the center of our solar system. Thanks to the sun, the planets in the solar system do not scatter and move in their orbits. It is very hot, the temperature on its surface is about 6,000 degrees Celsius.",
	"Mercury – this is the closest planet to the Sun. It is the smallest planet and is made of rock. It is so close to the Sun that it only takes 88 days for it to complete its orbit and is much hotter than Earth.",
	"Venus – is the next planet from the Sun after Mercury. It is also made of rock. Like Earth, Venus has an atmosphere (air) around it, but it is a lot thicker than Earth’s and Venus is permanently covered in clouds. Venus is the hottest planet and has an average temperature of 460°C. It is about the same size as Earth. It takes 225 days to travel around the Sun.",
	"Earth – This is where we live! Earth is made of rock and is the only planet where water is liquid. The other planets are either too hot or too cold. Earth takes 365 days to travel around the Sun.",
	"Mars – is a little smaller than Earth, but a lot further out. It used to have an atmosphere like Earth and Venus, but it doesn’t have very much anymore. Mars is reddish in colour and is sometimes called ‘The Red Planet’. Mars takes 687 days to complete its orbit pf the Sun and the average temperature is -63°C.",
	"Jupiter –is the largest planet in the Solar System. You could fit 1,321 Earths inside Jupiter. It is made of gas and is one of the four ‘gas giants’. Jupiter has 66 moons; one of them, Ganymede, is bigger than Mercury. Jupiter is five times as far from the Sun as the Earth is and takes almost 12 years to travel around the Sun.",
	"Saturn – is famous for its rings. The rings were first observed (with a telescope) in 1610 by Galileo and are made up of huge numbers of small lumps of ice and dust (mostly ice). The pieces in the rings may be as small as a millimetre or as large as a few metres across. Saturn is the second largest planet in the Solar System and is another one of the ‘gas giants’ like Jupiter. It takes 29.5 years to travel around the Sun.",
	"Uranus – is another of the ‘gas giants’. You could fit 63 planets the size of Earth inside Uranus. Uranus takes 84 years to orbit the Sun and is the coldest planet, with an average temperature of -220°C.",
	"Neptune – is the farthest planet from the Sun. It is 30 times as far from the sun as Earth and takes 165 years to travel around the Sun. Neptune is the last of the four ‘gas giants’ and is 58 times the volume of Earth."
]